// <auto-generated />
namespace tuto.webapi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedateend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedateend));
        
        string IMigrationMetadata.Id
        {
            get { return "201608311443336_change-dateend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
